Testing workflows

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,24 +1,103 @@
 name: Test
 
-concurrency:
-  group: ${{ github.workflow }}-${{ inputs.run-id || github.run_id }}
-  cancel-in-progress: true
+permissions:
+  contents: read
+  checks: read
 
 on:
-  push:
   workflow_call:
     inputs:
-      run-id:
-        type: string
+      pr-number:
         required: true
+        type: string
+      runs-on:
+        type: string
+        default: ubuntu-latest
+      baseline:
+        type: boolean
+        default: false
+  workflow_dispatch:
+    inputs:
+      pr-number:
+        type: string
+        description: The pull request from where to download Bun
+        required: true
+      runs-on:
+        type: string
+        description: The runner used to run the tests
+        default: ubuntu-latest
+      baseline:
+        type: boolean
+        description: If the baseline build should be used
+        default: false
 
 jobs:
   test:
-    runs-on: ubuntu-latest
+    name: Test
+    runs-on: ${{ inputs.runs-on }}
     steps:
-      - uses: actions/download-artifact@v4
+      - name: Checkout
+        uses: actions/checkout@v4
         with:
-          run-id: ${{ inputs.run-id || '8623134412' }}
-          # pattern: bun-*
-      - run: |
-          ls -la
+          sparse-checkout: |
+            package.json
+            bun.lockb
+            test
+            packages/bun-internal-test
+      - name: Setup Environment
+        shell: bash
+        run: |
+          echo "${{ inputs.pr-number }}" > pr-number.txt
+      - name: Download Bun
+        uses: dawidd6/action-download-artifact@v3
+        with:
+          name: bun-${{ runner.os == 'macOS' && 'darwin' || runner.os == 'Windows' && 'windows' || 'linux' }}-${{ runner.arch == 'X64' && 'x64' || 'aarch64' }}${{ inputs.baseline && '-baseline' || '' }}
+          path: ${{ runner.temp }}/bun
+          github_token: ${{ github.token }}
+          pr: ${{ inputs.pr-number }}
+          workflow_search: true
+          workflow_conclusion: completed
+          check_artifacts: true
+          search_artifacts: true
+      - name: Setup Bun
+        shell: bash
+        run: |
+          unzip -d /usr/local/bin ${{ runner.temp }}/bun/bun-*.zip
+          mv /usr/local/bin/bun-*/bun /usr/local/bin/bun
+          which bun
+          bun --version
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+      - name: Install Dependencies
+        shell: bash
+        run: |
+          bun install
+          bun install --cwd test
+          bun install --cwd packages/bun-internal-test
+      - name: Run Tests
+        id: test
+        shell: bash
+        env:
+          TMPDIR: ${{ runner.temp }}
+          BUN_FEATURE_FLAG_INTERNAL_FOR_TESTING: "true"
+          SMTP_SENDGRID_SENDER: ${{ secrets.SMTP_SENDGRID_SENDER }}
+          TLS_MONGODB_DATABASE_URL: ${{ secrets.TLS_MONGODB_DATABASE_URL }}
+          TLS_POSTGRES_DATABASE_URL: ${{ secrets.TLS_POSTGRES_DATABASE_URL }}
+        run: |
+          node packages/bun-internal-test/src/runner.node.mjs || true
+      - name: Upload Results
+        uses: actions/upload-artifact@v4
+        with:
+          name: results
+          path: |
+            test-report.*
+            pr-number.txt
+          if-no-files-found: error
+          overwrite: true
+      - name: Fail
+        if: ${{ steps.test.outputs.failing_tests != ''}}
+        run: |
+          echo "Failing tests: ${{ steps.test.outputs.failing_tests }}"
+          exit 1
